My Doxygen: ec.lab.ICalculator Class Reference
ec.lab.ICalculator Class Reference
This is the interface for Calculator class.
Public Member Functions
int sum (int a, int b)
Compute and return the sum of two integers.
int subtraction (int a, int b)
Compute and return the difference of two operands.
int multiplication (int a, int b)
Compute and return the multiplication of two integers.
int divison (int a, int b) throws Exception
Compute and return the devision of two integers.
boolean equalIntegers (int a, int b)
Check if two integer operands are equal.
Detailed Description
This is the interface for Calculator class.
Definition at line 9 of file ICalculator.java.
Member Function Documentation
divison()
int ec.lab.ICalculator.divison (int a, int b) throws Exception
Compute and return the devision of two integers.
Parameters
a
b
Returns
a/b
Exceptions
Exception if b == 0
Referenced by ec.lab.CalTest2.testDivisionException(), ec.lab.CalTest.testDivisionException(), ec.lab.CalTest2.testDivison(), and ec.lab.CalTest.testDivison().
equalIntegers()
boolean ec.lab.ICalculator.equalIntegers (int a, int b)
Check if two integer operands are equal.
Parameters
a
b
Returns
a==b
Referenced by ec.lab.CalTest.testEqual().
multiplication()
int ec.lab.ICalculator.multiplication (int a, int b)
Compute and return the multiplication of two integers.
Parameters
a
b
Returns
a*b
subtraction()
int ec.lab.ICalculator.subtraction (int a, int b)
Compute and return the difference of two operands.
Parameters
a
b
Returns
a-b
sum()
int ec.lab.ICalculator.sum (int a, int b)
Compute and return the sum of two integers.
Parameters
a
b
Returns
a+b
Referenced by ec.lab.MyCalculator.main(), ec.lab.CalTest2.testSum(), and ec.lab.CalTest.testSum().
The documentation for this class was generated from the following file:
src/ec/lab/ICalculator.java